#ifndef _COMMAND_HEADER_H_
#define _COMMAND_HEADER_H_

#include "txCommandSystem.h"
#include "txCommand.h"

#include "CommandCharacterManagerPlayerLogin.h"
#include "CommandCharacterManagerCreateCharacter.h"
#include "CommandCharacterManagerNotifyPlayerOffline.h"
#include "CommandCharacterManagerDestroyCharacter.h"
#include "CommandCharacterManagerRobotLogin.h"

#include "CommandRoomManagerCreateRoom.h"
#include "CommandRoomManagerDestroyRoom.h"

#include "CommandCharacterNotifyBanker.h"
#include "CommandCharacterJoinRoom.h"
#include "CommandCharacterLeaveRoom.h"
#include "CommandCharacterStartGame.h"
#include "CommandCharacterNotifyOtherPlayerOffline.h"
#include "CommandCharacterNotifyOtherPlayerLeaveRoom.h"
#include "CommandCharacterNotifyOtherPlayerJoinRoom.h"
#include "CommandCharacterReady.h"
#include "CommandCharacterNotifyOtherPlayerReady.h"
#include "CommandCharacterReorderMahjong.h"
#include "CommandCharacterNotifyAllGetStartDone.h"
#include "CommandCharacterAskDrop.h"
#include "CommandCharacterGetMahjong.h"
#include "CommandCharacterNotifyOtherPlayerGetMahjong.h"
#include "CommandCharacterAskAction.h"
#include "CommandCharacterNotifyOtherPlayerReorderMahjong.h"
#include "CommandCharacterDrop.h"
#include "CommandCharacterNotifyOtherPlayerDrop.h"
#include "CommandCharacterPlayerHu.h"
#include "CommandCharacterGang.h"
#include "CommandCharacterNotifyOtherPlayerGang.h"
#include "CommandCharacterPeng.h"
#include "CommandCharacterNotifyOtherPlayerPeng.h"
#include "CommandCharacterPass.h"
#include "CommandCharacterNotifyOtherPlayerPass.h"
#include "CommandCharacterNotifyOtherPlayerAskAction.h"
#include "CommandCharacterNotifyOtherPlayerAskDrop.h"
#include "CommandCharacterMahjongEnd.h"
#include "CommandCharacterContinueGame.h"
#include "CommandCharacterNotifyOtherPlayerContinueGame.h"
#include "CommandCharacterGetHua.h"
#include "CommandCharacterNotifyOtherPlayerGetHua.h"
#include "CommandCharacterGetStartDone.h"

#include "CommandRoomNotifyPlayerReady.h"
#include "CommandRoomNotifyPlayerLeave.h"
#include "CommandRoomNotifyPlayerJoin.h"
#include "CommandRoomStartGame.h"
#include "CommandRoomNotifyPlayerOffline.h"
#include "CommandRoomRequestDrop.h"
#include "CommandRoomConfirmAction.h"
#include "CommandRoomNotifyPlayerContinueGame.h"
#include "CommandRoomNotifyPlayerGetStartDone.h"

#include "CommandServerNotifyAcceptedClient.h"

#endif